---
title: "MotionChart"
author: "Andres Terreros and Yenny Webb-Vargas"
date: "Friday, October 17, 2014"
output: html_document
---

This is a test to run the ggvis plot

```{r setOptions, message=FALSE, echo=FALSE}
library(googleVis)
op <- options(gvis.plot.tag='chart')
```

```{r echo=FALSE}
enejul<-read.csv('http://ywebbvar.github.io/Terreros/enejul.csv',header=T)
vis<-gvisMotionChart(enejul,idvar='DESCRIPCION',timevar='Año')
mystate<-'
+ {"yZoomedIn":false,"uniColorForNonSelected":false,"playDuration":15000,"orderedByY":false,"yZoomedDataMax":32,"sizeOption":"_UNISIZE","xAxisOption":"_ALPHABETICAL","colorOption":"_UNIQUE_COLOR","xZoomedDataMin":0,"duration":{"timeUnit":"Y","multiplier":1},"iconType":"VBAR","dimensions":{"iconDimensions":["dim0"]},"time":"2009","xLambda":1,"nonSelectedAlpha":0.4,"iconKeySettings":[{"key":{"dim0":"CAMARON"}}],"yLambda":1,"xZoomedDataMax":11,"xZoomedIn":false,"showTrails":false,"orderedByX":true,"yZoomedDataMin":0,"yAxisOption":"2"}
+'
vis<-gvisMotionChart(enejul,idvar='DESCRIPCION',timevar='Año',options=list(state=mystate))
```

```{r results='asis'}
print(vis, 'chart')
```